//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class act
    {
        public int act_id { get; set; }
        public string act_tarids { get; set; }
        public string act_tartablename { get; set; }
        public string act_userIP { get; set; }
        public string act_username { get; set; }
        public string act_useraction { get; set; }
        public string act_sqlstr { get; set; }
        public Nullable<System.DateTime> act_datetime { get; set; }
        public string act_deptname { get; set; }
        public string act_userrolename { get; set; }
        public string act_DETAIL { get; set; }
    }
}
