//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_list
    {
        public string id { get; set; }
        public string application_program { get; set; }
        public string school_code { get; set; }
        public string school_year { get; set; }
        public Nullable<System.DateTime> application_start_data { get; set; }
        public Nullable<System.DateTime> application_end_data { get; set; }
        public string application_status { get; set; }
        public string prize_level { get; set; }
        public Nullable<bool> is_difficult_stu { get; set; }
        public string score_kao_ping_lowest { get; set; }
        public string nianji_score_rank { get; set; }
        public string banji_score_rank { get; set; }
        public string danke_lowest { get; set; }
        public string pinjun_lowest { get; set; }
        public Nullable<bool> is_fail_a_exam { get; set; }
        public Nullable<bool> is_punishment { get; set; }
        public Nullable<bool> once_is_punishment { get; set; }
        public string suitable_object { get; set; }
        public string project_intro { get; set; }
        public Nullable<bool> instructor_audit { get; set; }
        public string instructor { get; set; }
        public Nullable<bool> xuegong_audit { get; set; }
        public string xuegong { get; set; }
        public string dept_approver { get; set; }
        public Nullable<bool> dept_audit { get; set; }
        public Nullable<bool> is_instructor_audit { get; set; }
        public Nullable<bool> is_dept_audit { get; set; }
        public bool audit { get; set; }
        public Nullable<bool> @lock { get; set; }
    }
}
