//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string id { get; set; }
        public string dept_name { get; set; }
        public string dept_code { get; set; }
        public string subject_code { get; set; }
        public string connect_user { get; set; }
        public string dept_director { get; set; }
        public Nullable<System.DateTime> found_time { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string website { get; set; }
        public string introduction { get; set; }
        public Nullable<int> numofyanjiusheng { get; set; }
        public Nullable<int> numofboshisheng { get; set; }
        public Nullable<int> numofCNBooks { get; set; }
        public Nullable<int> numofFLBooks { get; set; }
        public Nullable<int> numofCNQikan { get; set; }
        public Nullable<int> numofFLQikan { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> audit { get; set; }
        public Nullable<byte> @lock { get; set; }
        public Nullable<int> Lab_equipment_count { get; set; }
        public string address { get; set; }
        public Nullable<decimal> Lab_equipment_property { get; set; }
        public string admit_unit { get; set; }
        public Nullable<int> numstaff { get; set; }
        public Nullable<int> numproject { get; set; }
        public Nullable<int> numarchievement { get; set; }
        public Nullable<int> numaward { get; set; }
        public Nullable<int> numreflection { get; set; }
    }
}
