//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_App
    {
        public string ID { get; set; }
        public string app_code { get; set; }
        public string app_name { get; set; }
        public string app_nameEn { get; set; }
        public string app_type { get; set; }
        public string dept_Code { get; set; }
        public string proc_name { get; set; }
        public string host_url { get; set; }
        public Nullable<bool> audit { get; set; }
        public Nullable<int> listorder { get; set; }
        public string parent_appcode { get; set; }
    }
}
