//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Roles
    {
        public string ID { get; set; }
        public string role_name { get; set; }
        public int role_AuthorRights { get; set; }
        public string DataScale { get; set; }
        public Nullable<bool> audit { get; set; }
        public Nullable<System.DateTime> ntime { get; set; }
        public string sitemap { get; set; }
    }
}
