//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public string id { get; set; }
        public string user_code { get; set; }
        public string user_name { get; set; }
        public string user_realname { get; set; }
        public string user_roles_code { get; set; }
        public string user_dept_code { get; set; }
        public string user_telphone { get; set; }
        public string user_password { get; set; }
        public Nullable<System.DateTime> regdatetime { get; set; }
        public string lastApp { get; set; }
        public string authApps { get; set; }
        public string authRights { get; set; }
        public Nullable<System.DateTime> lastLoginDatetime { get; set; }
        public string lastLoginIP { get; set; }
        public Nullable<bool> useRolesitemap { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<bool> audit { get; set; }
    }
}
