//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoprojMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_students
    {
        public string id { get; set; }
        public string school_code { get; set; }
        public string student_name { get; set; }
        public string grade { get; set; }
        public string dept { get; set; }
        public string major { get; set; }
        public string banji { get; set; }
        public string gender { get; set; }
        public string nation { get; set; }
        public Nullable<System.DateTime> born_date { get; set; }
        public string telephone { get; set; }
        public string politicstatus { get; set; }
        public string ID_card { get; set; }
        public string native_place { get; set; }
        public string address { get; set; }
        public string home_telephone { get; set; }
        public Nullable<System.DateTime> rollin_date { get; set; }
        public string dormitory { get; set; }
        public string imageurl { get; set; }
        public Nullable<bool> audit { get; set; }
        public Nullable<bool> @lock { get; set; }
    }
}
